### ISSUE TITLE
JAVBus Actor Pictures Not Downloading

### ISSUE THREAD

**Issue by fidofido300** [Wizell/JAVMovieScraper#17]
Latest Build Alpha 0.3.0
Scrapes Ok But When writing to disk gives following error.

Writing .actor images into C:\Download\torrent\Hidden\process\T28-515
java.io.IOException: Server returned HTTP response code: 403 for URL: https://pics.javbus.com/actress/q44_a.jpg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1489)
	at moviescraper.doctord.model.dataitem.Actor.writeImageToFile(Actor.java:38)
	at moviescraper.doctord.model.Movie.writeActorImagesToFolder(Movie.java:589)
	at moviescraper.doctord.model.Movie.writeToFile(Movie.java:552)
	at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:107)
	at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:36)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Wizell** [comment]
I tried to reproduced the error but i cannot. Can you confirm that you still encounter the error ?

**Comment by fidofido300** [comment]
yes I can Confirm
 it Gives the same error

**Comment by DarkMask100** [comment]
I've had the same issue, but it only seems to apply if the Actor image was not initially grabbed during scraping. Usually this happens when JavBus does not have any actors listed for the title but another source does.

**Comment by fidofido300** [comment]
But When you look at the links they point at secure https:// location at Javbus.com

**Comment by DarkMask100** [comment]
@Wizell were you able to reproduce during your testing? While I haven't tried the latest release, I still encounter this issue.
