### ISSUE TITLE
Scraper cannot read some generated nfo files

### ISSUE THREAD

**Issue by test9801** [Wizell/JAVMovieScraper#20]
v0.3.0-idol was able to scrap these 3 movies correctly:
GASO-0082 / IPZ-971 / SDMT-385

But was not able to read the generated NFO file, the following error was in the output window - 

java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at moviescraper.doctord.model.dataitem.Thumb.setThumbURL(Thumb.java:137)
	at moviescraper.doctord.model.dataitem.Thumb.<init>(Thumb.java:80)
	at moviescraper.doctord.controller.xmlserialization.KodiXmlActorBean.toActor(KodiXmlActorBean.java:49)
	at moviescraper.doctord.controller.xmlserialization.KodiXmlMovieBean.toMovie(KodiXmlMovieBean.java:138)
	at moviescraper.doctord.controller.SelectFileListAction.readMovieFromNfoFile(SelectFileListAction.java:149)
	at moviescraper.doctord.controller.SelectFileListAction.handleNewSelection(SelectFileListAction.java:94)
	at moviescraper.doctord.controller.SelectFileListAction.valueChanged(SelectFileListAction.java:45)
	at javax.swing.JList.fireSelectionValueChanged(Unknown Source)
	at javax.swing.JList$ListSelectionHandler.valueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
	at javax.swing.JList.setValueIsAdjusting(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Movie Size: 0

[GASO-0082.nfo.txt](https://github.com/Wizell/JAVMovieScraper/files/1510919/GASO-0082.nfo.txt)
[IPZ-971.nfo.txt](https://github.com/Wizell/JAVMovieScraper/files/1510920/IPZ-971.nfo.txt)

**Comment by Still34** [comment]
Same with many of my collections using the latest pre-release.

**Comment by DoctorD1501** [comment]
I fixed this today in the main project which has this branch's changes merged in:

https://github.com/DoctorD1501/JAVMovieScraper/commit/9258676377721bf9d182b9a6af4475e35adf5530

I have no idea how to do a release anymore though using Gradle, but I made Wizell have access so he should be able to push out new commits / releases from there.
