### ISSUE TITLE
java.io.IOException: Server returned HTTP response code: 403 for URL: https://i.datavimg.com/images/stars/

### ISSUE THREAD

**Issue by ianmargarone** [Wizell/JAVMovieScraper#25]
Hi,

Whena scraping and it returns the thumbs etc it then fails to add the img and poster. Please see log output below:

java.io.IOException: Server returned HTTP response code: 403 for URL: https://i.datavimg.com/images/stars/120/16923.jpg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at moviescraper.doctord.controller.FileDownloaderUtilities.getImageFromUrl(FileDownloaderUtilities.java:41)
	at moviescraper.doctord.model.ImageCache.getImageFromCache(ImageCache.java:29)
	at moviescraper.doctord.model.dataitem.Thumb.getThumbImage(Thumb.java:282)
	at moviescraper.doctord.view.renderer.ActressListRenderer.getImageIconForLabelName(ActressListRenderer.java:136)
	at moviescraper.doctord.view.renderer.ActressListRenderer.getListCellRendererComponent(ActressListRenderer.java:60)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(Unknown Source)
	at javax.swing.JComponent.getPreferredSize(Unknown Source)
	at javax.swing.ScrollPaneLayout.layoutContainer(Unknown Source)
	at java.awt.Container.layout(Unknown Source)
	at java.awt.Container.doLayout(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validate(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

It seems that https://i.datavimg.com is longer active. Is there a workaround since it prevents the movie posters from being downloaded as it bails before hand.

Thanks.

**Comment by ianmargarone** [comment]
Bump

**Comment by Cutters1982** [comment]
Data18 seem to now be blocking hotlinking to the performer images

**Comment by Wizell** [comment]
Issue will be followed in original repository.
